"""Add SystemAdmins

Revision ID: 7c7508c3b561
Revises: 5bacfca39946
Create Date: 2026-06-12 10:28:31.054683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c7508c3b561'
down_revision: Union[str, Sequence[str], None] = '5bacfca39946'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_admins_email'), 'system_admins', ['email'], unique=True)
    op.create_index(op.f('ix_system_admins_id'), 'system_admins', ['id'], unique=False)
    op.create_index(op.f('ix_system_admins_username'), 'system_admins', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_admins_username'), table_name='system_admins')
    op.drop_index(op.f('ix_system_admins_id'), table_name='system_admins')
    op.drop_index(op.f('ix_system_admins_email'), table_name='system_admins')
    op.drop_table('system_admins')
    # ### end Alembic commands ###
