"""Add attendance_policy_id to Employee

Revision ID: 947415a277e5
Revises: d518c88ee614
Create Date: 2026-06-17 12:52:34.485480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '947415a277e5'
down_revision: Union[str, Sequence[str], None] = 'd518c88ee614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boms', 'amount')
    op.drop_column('boms', 'payroll_id')
    op.drop_column('boms', 'account_id')
    op.create_foreign_key(None, 'employees', 'attendance_policies', ['attendance_policy_id'], ['id'])
    op.alter_column('orders', 'remarks',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('orders', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('orders', 'remarks',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.add_column('boms', sa.Column('account_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('boms', sa.Column('payroll_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('boms', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
