"""sync

Revision ID: ade3a65ef2c0
Revises: f861efe706e7
Create Date: 2026-06-17 22:29:41.515188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade3a65ef2c0'
down_revision: Union[str, Sequence[str], None] = 'f861efe706e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'approval_documents', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'approval_documents', type_='foreignkey')
    # ### end Alembic commands ###
