"""add fields to items for smt domain

Revision ID: b8b4cdcf53d7
Revises: 7c7508c3b561
Create Date: 2026-06-16 22:35:45.021981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b4cdcf53d7'
down_revision: Union[str, Sequence[str], None] = '7c7508c3b561'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_emp_no'), 'audit_logs', ['emp_no'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_resource'), 'audit_logs', ['target_resource'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_foreign_key(None, 'common_codes', 'common_code_groups', ['group_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'common_codes', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_resource'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_emp_no'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_type'), table_name='audit_logs')
    # ### end Alembic commands ###
