"""Add calculation basis to Payroll

Revision ID: cc97d95e3d5e
Revises: 5054ddc0b858
Create Date: 2026-06-17 14:12:34.975138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc97d95e3d5e'
down_revision: Union[str, Sequence[str], None] = '5054ddc0b858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
