"""Add Project and JournalEntryLine dimensions

Revision ID: f861efe706e7
Revises: e85ddc7dba15
Create Date: 2026-06-17 16:07:54.950649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f861efe706e7'
down_revision: Union[str, Sequence[str], None] = 'e85ddc7dba15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'journal_entry_lines', 'clients', ['client_id'], ['id'])
    op.create_foreign_key(None, 'journal_entry_lines', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'journal_entry_lines', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entry_lines', type_='foreignkey')
    op.drop_constraint(None, 'journal_entry_lines', type_='foreignkey')
    op.drop_constraint(None, 'journal_entry_lines', type_='foreignkey')
    # ### end Alembic commands ###
