version = 5.6.0
archive_dir = /etc/letsencrypt/archive/home.minstudio.app
cert = /etc/letsencrypt/live/home.minstudio.app/cert.pem
privkey = /etc/letsencrypt/live/home.minstudio.app/privkey.pem
chain = /etc/letsencrypt/live/home.minstudio.app/chain.pem
fullchain = /etc/letsencrypt/live/home.minstudio.app/fullchain.pem
[renewalparams]
account = 71d769aa3b27162cd3ba2afa40936b35
rsa_key_size = 4096
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
home.minstudio.app = /var/www/certbot
[acme_renewal_info]
ari_retry_after = 2026-06-21T14:10:46
